name: 'Match Lines'
description: 'GitHub Action to match lines against a matcher'
author: 'PayPay'
inputs:
  target_file:
    required: true
    description: 'File to be checked.'
  matcher:
    required: true
    description: 'Multiline with regular expression.'
  allow_failure:
    description: 'Makes the Action fail on match.'
    default: false
    required: false
outputs:
  match_count:
    description: 'Count of matched lines.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: blue
  icon: check-circle